version: "3.8"

services:
  app:
    container_name: app-marketplace
    build: ./
    command: ./wait-for-postgres.sh db ./bin/app
    ports:
      - 8000:8000
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGSSLMODE=disable
      - HTTP_PORT=8000
    depends_on:
      - db

  db:
    container_name: postgres-marketplace
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

